version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      # haria las actualizaciones semanalmente los lunes a las 00:00
      # interval: "weekly"
      # time: "00:00"
      # day: "monday"

      # Para cada 15 d√≠as, Dependabot no soporta "biweekly" directamente.
      # Puedes usar "cron" para lograrlo:
      interval: "cron"
      cronjob: "0 0 */15 * *"
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
